afterparty/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.homepage.urls')),
    path('dashboard/', include('apps.dashboard.urls')),
    path('api/', include('apps.api.urls')),
]

apps/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.index, name='index'),
    path('festival-profile/', views.festival_profile, name='festival_profile'),
    path('engagement/', views.engagement, name='engagement'),
    path('activity-map/', views.activity_map, name='activity_map'),
]

apps/homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'
urlpatterns = [
    path('', views.homepage, name='index'),
    path('attendee/<str:user_id>/', views.attendee_list, name='playlist'),
    path('edcvegas/', views.edc, name='edc'),
]

apps/homepage/views.py
import uuid

from django.http import Http404
from django.shortcuts import render, get_object_or_404

from apps.api.models import Attendee, PlaylistEntry
from apps.api.views import process_data_events


# Create your views here.
def homepage(request):
    return render(request, 'homepage/index.html')


def attendee_list(request, user_id):
    process_data_events()

    try:
        _uuid = uuid.UUID(user_id)
    except ValueError:
        raise Http404('Invalid user ID')

    attendee = get_object_or_404(Attendee, user_id=_uuid)
    tracks = PlaylistEntry.objects.filter(attendee__user_id=attendee.user_id)

    print()
    context = {
        'entries': tracks,
        'event_title': 'EDC Vegas 2018',
    }
    return render(request, 'homepage/attendeePlaylist.html', context)


def edc(request):
    return render(request, 'homepage/edc.html')

apps/homepage/templates/homepage/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>After Party</title>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans|Ramabhadra" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
  <style>
    * {
      padding: 0;
      margin: 0;
      font-family: 'Open Sans', sans-serif;
      box-sizing: border-box;
    }

    .title {
      font-family: 'Ramabhadra', sans-serif;
      color: #C711D4;
      text-transform: lowercase;
      font-size: 6em;
    }

    .copy {
      font-family: 'Open Sans', sans-serif;
      font-size: 2em;
      margin-bottom: 1.5em;
    }

    #hero {
      height: 100vh;
      width: 100vw;
      background: url({% static 'homepage/hero.jpg' %});
      background-position: 0 0;
      background-repeat: no-repeat;
      background-size: cover;
      display: table-cell;
      vertical-align: middle;
    }

    #content {
      margin: auto;
      text-align: center;
    }

    .links {
      font-size: 1.35em;
      color: #C711D4;
    }

    a {
      text-decoration: none;
      color: inherit;
    }

    a:hover {
      text-decoration: underline;
    }

    .links > li {
      display: inline;
    }

    .links > li:first-of-type {
      margin-right: 15em;
    }

    .floating-card {
      position: relative;
      -webkit-box-shadow: 0px 5px 10px 0px rgba(0,0,0,0.4);
      -moz-box-shadow: 0px 5px 10px 0px rgba(0,0,0,0.4);
      box-shadow: 0px 5px 10px 0px rgba(0,0,0,0.4);
      max-width: 800px;
      margin: auto;
    }

    @media only screen and (max-width: 480px) {
      .floating-card {
        margin: 0.5em;
      }
    }
  </style>
  {% block styles %}{% endblock %}
</head>
<body>
    <div id="hero">
      <div id="content">
      {% block content %}{% endblock %}
      </div>
    </div>
</body>
</html>

apps/homepage/templates/homepage/attendeePlaylist.html
{% extends 'homepage/_base.html' %}

{% block styles%}
<style>
  .brand-name {
    color: #C711D4;
    font-weight: bold;
  }

  .playlist {
    background: rgba(255, 255, 255, 0.5);
    padding: 1em 2em;
    overflow-y: scroll;
    height: 55vh;
  }

  .playlist__header {
    background: rgba(255, 255, 255, 0.75);
    vertical-align: middle;
    font-size: 1.75em;
    padding: 0.5em;
    font-family: 'Ramabhadra', sans-serif;
  }

  .playlist__footer {
    color: rgba(0,0,0,0.4);
    position: absolute;
    bottom: 0.5em;
    left: 0;
    right: 0;
    text-align: center;
  }

  .entry {
    line-height: 3em;
    vertical-align: middle;
  }

  .stage {
    display: inline;
    float: left;
    color: rgba(0,0,0,0.4);
    margin-right: 0.5em;
  }

  .track {
    text-align: left;
  }

  .track__title {
    font-size: 1.2em;
    font-weight: bold;
  }

  .track__artist::before {
    content: ' - ';
  }

  .vendors {
    display: inline;
    float: right;
  }

  .vendors .fab {
    padding: 0 0 0 0.5em;
  }

  .fab::before {
    font-size: 1.25em;
  }

  @media only screen and (max-width: 480px) {
    .playlist {
      height: 75vh;
    }

    .entry {
      line-height: 2em;
    }

    .track__artist, .track__title {
      display: inline-block;
    }

    .track {
      padding-bottom: 0.75em;
    }

    .track__artist::before {
      content: '';
    }

    .fab::before {
      font-size: 1.75em;
    }
  }
</style>
{% endblock %}

{% block content %}
<div class="floating-card">
  <div class="playlist__header">your <strong>{{ event_title }}</strong> <span class="brand-name">afterparty</span>:</div>
  <div class="playlist">
  {% for playlist_entry in entries %}
    <div class="entry">
      <p class="stage">
        {{ playlist_entry.performance.location.name }}
      </p>
      <p class="vendors">
        <a href="#"><i class="fab fa-amazon"></i></a>
        <a href="#"><i class="fab fa-spotify"></i></i></a>
        <a href="#"><i class="fab fa-itunes-note"></i></a>
      </p>
      <p class="track">
          <span class="track__title">{{ playlist_entry.song.title }}</span><span class="track__artist">{{ playlist_entry.song.artist }}</span>
      </p>
    </div>
    {% endfor %}
    <div class="playlist__footer">

    </div>
  </div>
</div>
{% endblock %}

apps/homepage/templates/homepage/edc.html
{% extends 'homepage/_base.html' %}
{% load static %}

{% block styles %}
<style>
  img {
    width: auto;
    height: 450px;
  }

  .floating-card {
    background: rgba(255,255,255,0.8);
    min-height: 450px;
    max-width: initial;
  }
</style>
{% endblock %}

{% block content %}
<h2 class="title">
  EDC Vegas 2018
</h2>
<div class="floating-card">
  <img src="{% static 'homepage/mixmaster_kale.jpg' %}" alt="Mixmaster Kale">
  <h3 class="copy">
    with performances by up-and-comer<br>
    💿 <em>M I X M A S T E R &middot; K A L E</em> 📀
  </h3>
</div>
{% endblock %}

apps/homepage/templates/homepage/index.html
{% extends 'homepage/_base.html' %}

{% block content %}
<h1 class="title">
  AfterParty
</h1>
<h2 class="copy">
  Media curation for fans,
  <br>
  Business intelligence for producers.
</h2>
<ul class="links">
  <li><a href="{% url 'dashboard:index' %}">Festival Producer</a></li>
  <li><a href="#">Festival Attendee</a></li>
</ul>
{% endblock %}